### ISSUE TITLE
The 'start' script was not found (sdk_hook_not_found)

### ISSUE THREAD

**Issue by BSouzaDock** [slack-samples/bolt-python-custom-function-template#10]
I'm getting this error when running slack run in my workspace. Can anyone help me with this?

![image](https://github.com/slack-samples/bolt-python-custom-function-template/assets/96547309/da85a82e-efd9-47aa-8954-8ef3bdd17047)

From the logs I see the following:
```
DEBUG 2024/03/26 18:28:22.649034 failed to initialize slack.json configurations: Command for 'GetHooks' returned an error: exec: "pwsh": executable file not found in %!P(MISSING)ATH%!
(MISSING) (sdk_hook_invocation_failed)
```

Note: I'm having some problems running the slack cli on windows. For example: when I run slack run, some commands using "python3 ..." are executed. It turns out that on Windows the correct option would be "python..." (I solved this by going to the python installation folder and duplicating the executable to the name python3)

**Comment by BSouzaDock** [comment]
Update: I managed to solve the problem by installing powershell7 on the machine. The pwsh command is not recognized in other versions from what I understand.

So there are these 2 additional steps to work on Windows: duplicate the python.exe file to python3.exe, install powershell 7 and add the path "C:\Program Files\PowerShell\7" in the PATH environment variable

**Comment by zimeg** [comment]
Hey @BSouzaDock 👋 Going to transfer this over to [slackapi/python-slack-hooks](https://github.com/slackapi/python-slack-hooks) really quick then share a bit more detail!

**Comment by zimeg** [comment]
Good catch with the Powershell version! This was from a change in how hooks are executed in CLI `v2.18.0`. Now Powershell `v6` or newer to execute hooks successfully. And thank you for sharing the details on setting this up too! 🙌 

The issue of which runtime executable to use - `python3` vs `python` - is something we're currently exploring! We hope to make this an option you can configure for your system instead of duplicating and renaming Python versions 😓 

A workaround you can do on a project level is update your `slack.json` file with the executable name you want to use with this:

```json
{
  "hooks": {
    "get-hooks": "python -m slack_cli_hooks.hooks.get_hooks",
    "get-manifest": "python -m slack_cli_hooks.hooks.get_manifest",
    "start": "python -X dev -m slack_cli_hooks.hooks.start",
    "check-update": "python -m slack_cli_hooks.hooks.check_update"
  }
}
```

I know this isn't ideal and might be fragile in future updates, but hopefully this can be another workaround! Please let me know if any of this is giving you trouble though!
