### ISSUE TITLE
Buttons actions generated by messages sent through the step function, do not generate trigger_id

### ISSUE THREAD

**Issue by BSouzaDock** [slack-samples/bolt-python-custom-function-template#15]
Another problem I encountered is that in the payload returned by actions generated by the step function, there is no trigger_id. 

Due to this, I am having to send messages using another traditional bot's token after the step function is activated.

**Comment by BSouzaDock** [comment]
@WilliamBergamin ,

When the user executes the workflow, they receive an ephemeral message with 2 buttons.

I had done it the way you said, using a traditional bot. But I thought I could do it using the new way.

Thanks.

**Comment by WilliamBergamin** [comment]
I see, we don't have docs for this in python yet but the approach should be similar to what is [found here](https://api.slack.com/automation/interactive-modals#open-trigger)

You should be able to pass an `interactivity_pointer` field instead of a `trigger_id` this interactivity pointer value should be available in the payload of the `actions` resulting from a button click when the message with the button is posted using the "function token" not the "traditional bot's token"

Let me know this is solves your issue, we will need to document this
